<?php if (!$user) : ?>
	User <?php echo $this->escape($search) ?> not found
<?php else : ?>
	User <?php echo $this->escape($user->getUsername()) ?> has email address <?php echo $this->escape($user->getEmail()) ?><br />

	<?php if (!$pairs) : ?>
		No pair programming!
	<?php else : ?>
		Pair programmed with:
		<ul>
		<?php foreach ($pairs as $pair) : ?>
			<li><a href="/<?php echo $pair->getId() ?>"><?php echo $this->escape($pair->getUsername()) ?></a></li>
		<?php endforeach ?>
		</ul>
	<?php endif ?>
<?php endif ?>

<br />
<br />
<a href="/">List</a>