<?php if (!$user) : ?>
	User <?php echo $this->escape($search) ?> not found
<?php else : ?>
	User <?php echo $this->escape($user->getUsername()) ?> has email address <?php echo $this->escape($user->getEmail()) ?><br />

	<?php if (!$pairs) : ?>
		No pair programming!
	<?php else : ?>
		Pair programmed with:
		<ul>
		<?php foreach ($pairs as $pair) : ?>
			<li><a href="/<?php echo $pair->getId() ?>"><?php echo $this->escape($pair->getUsername()) ?></a></li>
		<?php endforeach ?>
		</ul>
	<?php endif ?>

	<?php if ($comments) : ?>
		Here's what people had to day:
		<ul>
		<?php foreach ($comments as $comment) :
			$author = $comment->getAuthor();
		?>
			<li><a href="/<?php echo $author->getId() ?>"><?php echo $this->escape($author->getUsername()) ?></a>: <?php echo $this->escape($comment->getcontent()) ?></li>
		<?php endforeach ?>
		</ul>
	<?php endif ?>

	<h4>Add a comment</h4>
	<form action="/comment" method="POST">
		<input type="hidden" name="aboutId" value="<?php echo $user->getId() ?>" />
		<label>Name:<br /><input type="text" name="authorName" /></label><br />
		</label>Comment:<br /><textarea name="content"></textarea></label><br />
		<input type="submit" value="Save" />
	</form>
<?php endif ?>

<br />
<br />
<a href="/">List</a>